"""
Canonical trading syscall spec for CTOS drivers.
Each driver must implement these methods with consistent shapes.
"""

from typing import Any, Dict, Iterable, Optional

class TradingSyscalls:
    def symbols(self) -> Iterable[str]: ...
    def exchange_limits(self) -> Dict[str, Any]: ...
    def fees(self) -> Dict[str, Any]: ...

    # Market data
    def subscribe_ticks(self, symbols): ...
    def subscribe_klines(self, symbol: str, timeframe: str): ...
    def get_orderbook(self, symbol: str, level: int = 50): ...

    # Trading
    def place_order(self, symbol: str, side: str, ord_type: str,
                    size: float, price: Optional[float] = None,
                    client_id: Optional[str] = None, **kwargs) -> Dict[str, Any]: ...
    def amend_order(self, order_id: str, **kwargs) -> Dict[str, Any]: ...
    def cancel_order(self, order_id: str) -> Dict[str, Any]: ...
    def cancel_all(self, symbol: Optional[str] = None) -> Dict[str, Any]: ...

    # Account
    def balances(self) -> Dict[str, float]: ...
    def positions(self) -> Dict[str, Any]: ...
    def transfer(self, **kwargs) -> Dict[str, Any]: ...
