mode: paper
default_exchange: okx
log_level: INFO
data:
  store: parquet
  path: data/
risk:
  max_notional_usd: 10000
  max_leverage: 3
  price_band_bps: 200
  kill_switch: true
exchanges:
  okx:
    account: default_okx
  binance:
    account: default_binance
  backpack:
    account: default_backpack
accounts:
  default_okx:
    keyref: okx_main
  default_binance:
    keyref: binance_main
  default_backpack:
    keyref: backpack_main
