keys:
  okx_main:
    api_key: YOUR_OKX_KEY
    api_secret: YOUR_OKX_SECRET
    passphrase: YOUR_OKX_PASSPHRASE
  binance_main:
    api_key: YOUR_BINANCE_KEY
    api_secret: YOUR_BINANCE_SECRET
  backpack_main:
    api_key: YOUR_BACKPACK_KEY
    api_secret: YOUR_BACKPACK_SECRET
  backpack:
    main:
      public_key: ...
      secret_key: ...
    arb_bot:
      public_key: ...
      secret_key: ...